#
# Helix Configuration
#
version: 1

definitions:
  defaults:
    # default repository. set to git remote repository before deployment
    - &defaultRepo "http://localhost/local/default.git"
    # local development repository.
    - &localRepo "http://localhost/local/default.git"

strains:
  - name: local-dev
    url: http://localhost:3000/
    code: *localRepo
    content: *localRepo
    static: *localRepo

  - name: default
    code: *defaultRepo
    content: *defaultRepo
    static: *defaultRepo
